### ISSUE TITLE
Should this repo be deprecated?

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell-Tests#11]
With https://github.com/PowerShell/PowerShell most of the tests are duplicated there, they are living and breathing. Is there a value in leaving this repo around?

**Comment by SteveL-MSFT** [comment]
@JamesWTruher is this a strict subset of what we have in PS/PS repo now?

**Comment by JamesWTruher** [comment]
I should think so - there may be some individual tests that aren't present, but this is certainly out of date enough to delete the repo

**Comment by SteveL-MSFT** [comment]
I'll update the README redirecting to PS/PS and will delete end of Aug
