### ISSUE TITLE
Question about code fragment in ClearRecycleBin.Tests.ps1

### ISSUE THREAD

**Issue by megamorf** [PowerShell/PowerShell-Tests#3]
In https://github.com/PowerShell/PowerShell-Tests/blob/master/Commands/Cmdlets/ClearRecycleBin.Tests.ps1 (83ec2c1) you have the following lines of code:

``` powershell
$currentDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$helperModule = Join-Path $currentDirectory "ClearRecycleBinHelperFunctions.psm1"
if (-not $helperModule)
{
    throw "Helper module $helperModule is not available."
}
Import-Module $helperModule -Force
```

Here you're not testing if the path to _ClearRecycleBinHelperFunctions.psm1_ exists but only if the string in _$helperModule_ is not empty/null. Why would you want to do that?

**Comment by JamesWTruher** [comment]
good catch
